Directory %{python3_sitelib}/__pycache__ must not be included.
According to the web page here:

https://docs.fedoraproject.org/en-US/packaging-guidelines/Python/

under the sections "Files To Include" and "Byte Compiling", we have the
following instructions:

Packagers SHOULD NOT simply glob everything under the sitelib or sitearch
directories.

and

You MUST NOT include the directories %{python3_sitearch}/__pycache__
or %{python3_sitelib}/__pycache__ because they are already owned by
the python3-libs package.

And indeed, this now causes problems like the following:

Error: Transaction check error:
  file /usr/lib/python3.7/site-packages/__pycache__ from install of kicad-100:5.1-1.fc30.x86_64 conflicts with file from package python3-configparser-3.7.1-2.fc30.noarch